# Generated by packaging/homebrew/render-formula.sh - do not edit by hand.
class Jack < Formula
  desc "Terminal text editor with tree-sitter highlighting and vim keys"
  homepage "https://github.com/rgsoda/jack-editor"
  version "0.13.8"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/rgsoda/jack-editor/releases/download/v0.13.8/jack-0.13.8-aarch64-apple-darwin.tar.gz"
      sha256 "7b4026c12578cf725309975cd9032152734bd27b699a232e9d373d489e6cf199"
    end
    on_intel do
      url "https://github.com/rgsoda/jack-editor/releases/download/v0.13.8/jack-0.13.8-x86_64-apple-darwin.tar.gz"
      sha256 "429a60e92746879acafb2de7a9cb5052d8f27597d4234d8c1b2a238c87ad01f3"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/rgsoda/jack-editor/releases/download/v0.13.8/jack-0.13.8-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "49b17c104a3ddee3911a03b71345f32a19595bdbef79b1a1dfb95ec66574810f"
    end
    on_intel do
      url "https://github.com/rgsoda/jack-editor/releases/download/v0.13.8/jack-0.13.8-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "a1cc4f9afd5f78510a6a14e083b1580daf71f118804f92860dfa61c13c1a66ed"
    end
  end

  def install
    bin.install "jack"
    # The icon, the desktop entry and the two scripts that install them: a
    # windowed editor wants a launcher entry as well as a binary, and a
    # bottled install has nowhere else to get them from.
    pkgshare.install "packaging/icon", "packaging/jack.desktop", "packaging/linux", "packaging/macos"
  end

  test do
    assert_match "jack #{version}", shell_output("#{bin}/jack --version")
  end
end
