# Generated by packaging/homebrew/render-formula.sh - do not edit by hand.
class Jack < Formula
  desc "Terminal text editor with tree-sitter highlighting and vim keys"
  homepage "https://github.com/rgsoda/jack-editor"
  version "0.13.3"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/rgsoda/jack-editor/releases/download/v0.13.3/jack-0.13.3-aarch64-apple-darwin.tar.gz"
      sha256 "e29a5d17273702c774ac452eda30458745aaad242a4a49309554c57e61fa5248"
    end
    on_intel do
      url "https://github.com/rgsoda/jack-editor/releases/download/v0.13.3/jack-0.13.3-x86_64-apple-darwin.tar.gz"
      sha256 "06ca9f1f1bf2a278f3885bd07a882c08c51dfbd9f47f06a5b42eb8b4f62cd8d6"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/rgsoda/jack-editor/releases/download/v0.13.3/jack-0.13.3-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "f8a87fdda814d20f5472e6d8591b08042d6beb0bfa6c935a5d03b3e6bc634a01"
    end
    on_intel do
      url "https://github.com/rgsoda/jack-editor/releases/download/v0.13.3/jack-0.13.3-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "e36ec24711955d173179d2e3c3410bbfb187cf28656b023455ec5cf6893ff09b"
    end
  end

  def install
    bin.install "jack"
  end

  test do
    assert_match "jack #{version}", shell_output("#{bin}/jack --version")
  end
end
