# Generated by packaging/homebrew/render-formula.sh - do not edit by hand.
class Jack < Formula
  desc "Terminal text editor with tree-sitter highlighting and vim keys"
  homepage "https://github.com/rgsoda/jack-editor"
  version "0.17.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/rgsoda/jack-editor/releases/download/v0.17.0/jack-0.17.0-aarch64-apple-darwin.tar.gz"
      sha256 "08fd6f7e19909790a04b5525b81aa96861d9d0ef0f622061cc28d1fd1eb96f3e"
    end
    on_intel do
      url "https://github.com/rgsoda/jack-editor/releases/download/v0.17.0/jack-0.17.0-x86_64-apple-darwin.tar.gz"
      sha256 "921464861afa22290471b45e4a44472499a8bcc15d8e09256c46e0dd76c98e49"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/rgsoda/jack-editor/releases/download/v0.17.0/jack-0.17.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "9ad01dfae2bf3526640e6ec2e0905b8c0c62e18655a0ef50db07688de7f3c1bd"
    end
    on_intel do
      url "https://github.com/rgsoda/jack-editor/releases/download/v0.17.0/jack-0.17.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "5b689678e41280bcd027a5a090760a9357a8fc5f4743082ff54b3b27da720118"
    end
  end

  def install
    bin.install "jack"
    # A second name for the same binary, which opens a window without being
    # asked: a launcher or a Dock item names a program and has nowhere to put
    # a flag.
    bin.install_symlink bin/"jack" => "jack-gui"
    # The icon, the desktop entry and the two scripts that install them: a
    # windowed editor wants a launcher entry as well as a binary, and a
    # bottled install has nowhere else to get them from.
    pkgshare.install "packaging/icon", "packaging/jack.desktop", "packaging/linux", "packaging/macos"
  end

  test do
    assert_match "jack #{version}", shell_output("#{bin}/jack --version")
  end
end
